packet-mask: "0x1/0x1"
listen-port: 9090
ignore-ip:
  - "192.168.0.0/16"
  - "172.16.0.0/12"
  - "10.0.0.0/8"
dns:
  listen-addr: "192.168.0.1:53"
  dns-timeout: 30
  local-resolver:
    - "114.114.114.114"
    - "10.0.0.1"
  proxy-resolver:
    - "8.8.8.8"
  cache:
    enable: true
    timeout: 30
shadowsocks:
  tcp-timeout: 120
  udp-timeout: 30
  pac-list:
    - "gfw-list.txt"
    - "custom-list.txt"
  servers:
    - remote-server: "65.49.196.94:20000"
      crypt: "AEAD_CHACHA20_POLY1305"
      Password: "123321A"
      kcptun:
        enable: false
        server: "65.49.196.94:20010"
        mode: "fast"
        thread: 4
        conn: 4
        autoexpire: 0
        mtu: 1350
        sndwnd: 128
        rcvwnd: 512
        datashard: -1
        parityshard: -1
        dscp: 0
        nocomp: false
        keep-alive-interval: 10
        keep-alive-timeout: 120
        sock-buf : 4194304
    - remote-server: "149.28.13.248:20001"
      crypt: "AEAD_CHACHA20_POLY1305"
      Password: "123321A"
      kcptun:
        enable: false
        server: "149.28.13.248:20011"
        mode: "fast"
        thread: 4
        conn: 4
        autoexpire: 0
        mtu: 1350
        sndwnd: 128
        rcvwnd: 512
        datashard: -1
        parityshard: -1
        dscp: 0
        nocomp: false
        keep-alive-interval: 10
        keep-alive-timeout: 120
        sock-buf : 4194304
