packet-mask: "0x1/0x1"
listen-port: 9090
ignore-ip:
  - "192.168.0.0/16"
  - "172.16.0.0/12"
dns:
  listen-addr: "192.168.0.1:53"
  dns-timeout: 30
  local-resolver:
    - "114.114.114.114"
    - "10.0.0.1"
  proxy-resolver:
    - "8.8.8.8"
    - "8.8.4.4"
shadowsocks:
  tcp-timeout: 120
  udp-timeout: 30
  pac-list:
    - "gfw-list.txt"
    - "custom-list.txt"
  servers:
    - remote-server: "10.0.0.51:20000"
      crypt: "AEAD_CHACHA20_POLY1305"
      Password: "123321A"
      kcptun:
        enable: true
        server: "10.0.0.51:20010"
        mode: "fast"
        thread: 4
        conn: 1
        autoexpire: 0
        mtu: 1350
        sndwnd: 128
        rcvwnd: 512
        datashard: -1
        parityshard: -1
        dscp: 0
        nocomp: false
        keep-alive: 10
        sock-buf : 4194304
    - remote-server: "10.0.0.51:20001"
      crypt: "AEAD_CHACHA20_POLY1305"
      Password: "123321A"
      kcptun:
        enable: true
        server: "10.0.0.51:20011"
        mode: "fast"
        thread: 4
        conn: 1
        autoexpire: 0
        mtu: 1350
        sndwnd: 128
        rcvwnd: 512
        datashard: -1
        parityshard: -1
        dscp: 0
        nocomp: false
        keep-alive: 10
        sock-buf : 4194304
