packet-mask: "0x1/0x1"
listen-port: 9090
dns:
  listen-addr: "192.168.0.1:53"
  dns-timeout: 60
  local-resolver:
    - "114.114.114.114"
  proxy-resolver:
    - "8.8.8.8"
    - "8.8.4.4"
shadowsocks:
  tcp-timeout: 120
  udp-timeout: 60
  pac-list:
    - "gfw-list.txt"
    - "gfw-list.txt"
  servers:
    - remote-server: "10.10.1.103:10000"
      crypt: "AEAD_CHACHA20_POLY1305"
      Password: "123321A"
      kcptun:
        enable: true
        server: "10.10.1.103:10010"
        crypt: "salsa20"
        mode: "fast"
        conn: 1
        autoexpire: 0
        mtu: 1350
        sndwnd: 128
        rcvwnd: 512
        datashard: 10
        parityshard: 3
        dscp: 0
        nocomp: false
        keep-alive: 10
        sock-buf : 4194304

