dns:
  listen-addr: "0.0.0.0:5300"
  local-resolver:
    - "114.114.114.114"
  proxy-resolver:
    - "8.8.4.4"
shadowsocks:
  listen-addr: "0.0.0.0:9090"
  tcp-timeout: 240
  udp-timeout: 120
  pac-list:
    - "gfw-list.txt"
    - "gfw-list.txt"
  servers:
    - remote-server: "10.0.0.51:10000"
      crypt: "AEAD_CHACHA20_POLY1305"
      Password: "123321A"
      kcptun:
        enable: false
        remote-server: "146.71.79.80:8446"
        key: "JumpJumpJump!!!"
        crypt: "salsa20"
        mode: "fast"
        conn: 1
        autoexpire: 0
        mtu: 1350
        sndwnd: 128
        rcvwnd: 512
        datashard: 10
        parityshard: 3
        dscp: 0
        nocomp: false

