packet-mask: "0x1/0x1"
routing-table: 100
listen-port: 9090
ignore-ip:

dns:
  listen-addr: "0.0.0.0:53"
  dns-timeout: 10
  local-resolver:
    - "127.0.0.11"
  proxy-resolver:
    - "127.0.0.11"
  send-num: 2
  cache: false
pac-list:
  - "pac-list.txt"
shadowsocks:
  servers:
  - enable: true
    remote-server: "192.168.1.2:20000"
    crypt: "AEAD_CHACHA20_POLY1305"
    Password: "123321A"
    tcp-timeout: 120
    udp-timeout: 30
    kcptun:
      enable: true
      server: "192.168.1.2:20010"
      mode: "fast"
      thread: 4
      conn: 4
      autoexpire: 0
      mtu: 1350
      sndwnd: 128
      rcvwnd: 512
      datashard: -1
      parityshard: -1
      dscp: 0
      nocomp: false
      keep-alive-interval: 10
      keep-alive-timeout: 120
      sock-buf : 4194304

